custom_logo:
  enabled: true
  image: /images/logo.jpg
menu:
  home: /
  about: /about/
  #tags: /tags/ || tags
  #categories: /categories/ || th
  archives: /archives/
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
#menu:
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

# Enable/Disable menu icons.
menu_icons:
  enable: true
