custom_logo:    #header logo
  enabled: true
  image: /images/logo.png
menu:
  home: / || home
  tags: /tags/ || tags
  archives: /archives/ || file
  github: https://github.com/littleee/ || github
  about: /about/ || user
#menu:
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

# Enable/Disable menu icons.
menu_icons: #菜单icon
  enable: false
