custom_logo:    #header logo
  enabled: true
  image: /images/logo.png
menu:
  home: / || home
  tags: /tags/ || tags
  archives: /archives/ || file
  github: https://github.com/littleee/ || github
  about: /about/ || user

# Enable/Disable menu icons.
menu_icons: #菜单icon
  enable: false
#head
show_count: true
head_title:
  enable: true
  title: HELLO, IM CORA
  subtitle: 三流代码 & 一流Bug
